### ISSUE TITLE
判断字符串为空，应该采用 str == ""，不能取字符串长度

### ISSUE THREAD

**Issue by xkeyideal** [gotail/strx#2]
虽然是字符串，也考虑一下性能

**Comment by fangpianqi** [comment]
> 虽然是字符串，也考虑一下性能

你好：
已修改，我是一名Java程序员，用Go的时间不长，会将一些我认为有用的东西放到gotail这个组织下，[gotail](https://github.com/gotail)，如果有兴趣，欢迎一起来搞。

**Comment by fangpianqi** [comment]
@xkeyideal 我做了一些实验，基于go的最新版本，用 == 与用 len 判断字符串空，得到的时间是一样的。

**Comment by xkeyideal** [comment]
赞一下，你很认真，我没有对此做过测试，也没有看过源码中 `len` 的实现
